stages:
  - build
  - deploy

.linux_build_template: &linux_build
  image: "${SIGHT_CI_UBUNTU20_10}:dev"
  stage: build
  dependencies: []
  before_script:
    # Create directory structure
    - sudo chown -R sight:sight .
    - mkdir -p $CI_PROJECT_DIR/install $CI_PROJECT_DIR/build $CI_PROJECT_DIR/archive
    # Merge the branch into dev.
    - >
      if [ -z "$CI_COMMIT_TAG" ] && [ "$CI_COMMIT_REF_NAME" != "dev" ] && [ "$CI_COMMIT_REF_NAME" != "master" ]; then
        git config user.name ${GITLAB_USER_ID}
        git config user.email ${GITLAB_USER_EMAIL}
        git fetch --all
        git checkout dev
        git reset --hard origin/dev
        git merge "origin/"${CI_COMMIT_REF_NAME} --no-commit --no-ff
      fi
    # Build the project on the merge result.
    - rm -rf $CI_PROJECT_DIR/archive/* $CI_PROJECT_DIR/build/* $CI_PROJECT_DIR/install/*
    - cd $CI_PROJECT_DIR/build/
    - >
      cmake $CI_PROJECT_DIR
      -G Ninja
      -DCMAKE_INSTALL_PREFIX=$CI_PROJECT_DIR/install
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
    - ninja
    # Install and build the package
    - ninja install
    - ninja package
    # Test if there is no hard coded path
    - echo "Search for hard coded path in cmake config files:"
    - grep -rn $CI_PROJECT_DIR --include="*.cmake" $CI_PROJECT_DIR/install || export exit_code=$?
    - if [[ $exit_code -ne 0 ]]; then echo "No hard coded path found."; else false; fi;
    # Retrieve package name and store it as environment files since inherited environment variable is experimental
    # and need to explicitly enabled (https://docs.gitlab.com/ee/ci/variables/#enable-inherited-environment-variables-core-only)
    - export ARCHIVE_FILE_PATH=$(find $CI_PROJECT_DIR/build -maxdepth 1 -iname '*.tar.zst' -type f -print -quit)
    - export ARCHIVE_NAME=$(basename -s .tar.zst ${ARCHIVE_FILE_PATH})
    - mv ${ARCHIVE_FILE_PATH} $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.tar.zst
    - echo "export ARCHIVE_NAME=${ARCHIVE_NAME}" > $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.env

build:debug-linux:
  <<: *linux_build
  variables:
    BUILD_TYPE: "Debug"
  script:
    - cat $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.env
    - ls -la $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.tar.zst
  artifacts:
    paths:
      # We cannot use ${DEBUG_ARCHIVE_NAME} here
      - $CI_PROJECT_DIR/archive/Debug_archive.env
      - $CI_PROJECT_DIR/archive/Debug_archive.tar.zst

build:release-linux:
  <<: *linux_build
  variables:
    BUILD_TYPE: "Release"
  script:
    - cat $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.env
    - ls -la $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.tar.zst
  artifacts:
    paths:
      # We cannot use ${RELEASE_ARCHIVE_NAME} here
      - $CI_PROJECT_DIR/archive/Release_archive.env
      - $CI_PROJECT_DIR/archive/Release_archive.tar.zst

build:relwithdebinfo-linux:
  <<: *linux_build
  variables:
    BUILD_TYPE: "RelWithDebInfo"
  script:
    - cat $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.env
    - ls -la $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.tar.zst
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}-SIGHTDEPS"
    paths:
      # We cannot use ${RELEASE_ARCHIVE_NAME} here
      - $CI_PROJECT_DIR/archive/RelWithDebInfo_archive.env
      - $CI_PROJECT_DIR/archive/RelWithDebInfo_archive.tar.zst

.linux_deploy_template: &linux_deploy
  image: "${SIGHT_CI_UBUNTU20_10}:dev"
  stage: deploy
  before_script:
    # Create directory structure
    - sudo chown -R sight:sight .
    - mkdir -p $CI_PROJECT_DIR/install $CI_PROJECT_DIR/build $CI_PROJECT_DIR/archive
    - source $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.env
    - >
      if [ -z "$CI_COMMIT_TAG" ] && [ "$CI_COMMIT_REF_NAME" != "dev" ] && [ "$CI_COMMIT_REF_NAME" != "master" ]; then
        curl -u${CONAN_USERNAME}:${CONAN_PASSWORD} -T $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.tar.zst "https://conan.ircad.fr/artifactory/data/sight-deps/${ARCHIVE_NAME}.tar.zst"
      else
        curl -u${CONAN_USERNAME}:${CONAN_PASSWORD} -T $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.tar.zst "https://conan.ircad.fr/artifactory/data/sight-deps/${ARCHIVE_NAME}-$CI_COMMIT_REF_NAME.tar.zst"
        curl -u${CONAN_USERNAME}:${CONAN_PASSWORD} -T $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.tar.zst "https://conan.ircad.fr/artifactory/data/sight-deps/sight-deps-${BUILD_TYPE}-latest-Linux-$CI_COMMIT_REF_NAME.tar.zst"
      fi

deploy:debug-linux:
  <<: *linux_deploy
  dependencies:
    - build:debug-linux
  variables:
    BUILD_TYPE: "Debug"
  when: manual
  script:
    - cat $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.env
    - ls -la $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.tar.zst
  artifacts:
    paths:
      # We cannot use ${DEBUG_ARCHIVE_NAME} here
      - $CI_PROJECT_DIR/archive/Debug_archive.env
      - $CI_PROJECT_DIR/archive/Debug_archive.tar.zst

deploy:release-linux:
  <<: *linux_deploy
  dependencies:
    - build:release-linux
  variables:
    BUILD_TYPE: "Release"
  when: manual
  script:
    - cat $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.env
    - ls -la $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.tar.zst
  artifacts:
    paths:
      # We cannot use ${RELEASE_ARCHIVE_NAME} here
      - $CI_PROJECT_DIR/archive/Release_archive.env
      - $CI_PROJECT_DIR/archive/Release_archive.tar.zst

deploy:relwithdebinfo-linux:
  <<: *linux_deploy
  dependencies:
    - build:relwithdebinfo-linux
  variables:
    BUILD_TYPE: "RelWithDebInfo"
  when: manual
  script:
    - cat $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.env
    - ls -la $CI_PROJECT_DIR/archive/${BUILD_TYPE}_archive.tar.zst
  artifacts:
    paths:
      # We cannot use ${RELWITHDEBINFO_ARCHIVE_NAME} here
      - $CI_PROJECT_DIR/archive/RelWithDebInfo_archive.env
      - $CI_PROJECT_DIR/archive/RelWithDebInfo_archive.tar.zst
